FROM ruby:<%= ruby_version %>-alpine<%= alpine_version %>
WORKDIR /<%= name %>
RUN apk update && apk upgrade
RUN apk add bash bash-completion build-base curl git postgresql-client postgresql-dev tzdata

ENV RUBY_YJIT_ENABLE=1
